### PR TITLE
fix: goto definition should find registration of simple keyword

### PR DESCRIPTION
**Pull request by mainej**
This was noticed while working on #1097. 

- ~I created an issue to discuss the problem I am trying to solve or an open issue already exists.~
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- ~I updated documentation if applicable (`docs` folder)~

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
I was almost sure there was a issue about allowing that, but I didn't find any, maybe we discussed somewhere on Slack

**Comment by mainej** [comment]
I searched on Slack, but I'm not seeing it. Let me know if you find anything. That code has been there from the very beginning, since `find-definition` was defined for keywords. It was announced [here](https://clojurians.slack.com/archives/CPABC1H61/p1612530939344500), FWIW.

**Comment by ericdallo** [comment]
> I was almost sure there was a issue about allowing that

Yeah, just to elaborate, I mean, I remember talking with someone which was requesting the feature of finding definition of a simple keyword, so I think it's good to go

**Comment by ericdallo** [comment]
Could you check integration tests failing @mainej ?

**Review by ericdallo — APPROVED** [review]
Sorry about the conflict, feel free to resolve and merge

**Pull request merged**
