### PR TITLE
Show caller for hover documentation

### PR DESCRIPTION
**Pull request by TheBlob42**
Fix for #1281 

I totally agree with @snoe on how the hover functionality should work, but I also see the value in the proposed solution at the end of the linked issue. This is my attempt to implement it. Since it is my first time diving into the clojure-lsp code there might be conventions or other things that I have not done "correctly". Please feel free to point everything out that you think could be solved in a better way (also when there are naming conventions etc.).

I would check the CHANGELOG.md and documentation once we have agreed on the code changes in general

- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
    - already existed
- [ ] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- [ ] I updated documentation if applicable (`docs` folder)

### CODE REVIEW

**Comment by TheBlob42** [comment]
I have another idea regarding the correct syntax highlighting of the calling-line:
Could we wrap it inside an annotated  code block? At least for the markdown case

image

We would add another newline since we can't inline a code block with syntax highlighting (to my knowledge), but we would get the correct highlighting for the function and arguments. The additional code block lines should be handled by the editor (Neovim is working on it, I guess VSCode already does this). What do you think @ericdallo ?

**Comment by ericdallo** [comment]
@TheBlob42 nice, the markdown idea is what I was expecting, but we should keep it at the first line, some editors like emacs has a hover preview feature which shows the first line of hover, so in this case would just show `calling:` which is not useful, maybe we should move `calling:` to the same line inside the code block or as a comment in the end of the first line or so, WDYT?

image

**Comment by TheBlob42** [comment]
I did not know about this Emacs feature (quite cool actually). Therefore your proposal of putting everything into the same line makes a lot of sense. I personally would prefer to put the `calling: ` element up front, to make it clear that this documentation is not for the element directly under the cursor. Putting it at the end of the line, would increase the "risk" for it to be overlooked or in cases of long function definitions even cut off.

I would love your input on how to insert it into the hover text. We could simply insert it (it should then be highlighted like a symbol), as a string (for some different highlighting) or my personal favorite with the `#_`  [macro](https://clojure.org/reference/reader#_dispatch) which should be highlighted as a comment and is the closest thing to an inline comment in Clojure. Or we use something else. WDYT?

image

image

image

**Comment by ericdallo** [comment]
I liked the `#_` one, I hope it will be clear to users, it's already better to what we have ATM which is nothing, so I think we can go with that option

**Comment by TheBlob42** [comment]
Sorry my rebasing auto closed this PR and I can't reopen it. I opened a new PR instead here #1735

**Comment by TheBlob42** [comment]
Reopen this PR

**Comment by TheBlob42** [comment]
Sorry my rebasing auto closed this PR and I don't understand how to reopen it :joy:
Please check the new PR with the latest state here #1735

**Pull request closed without merging**
