### PR TITLE
feat(nix-flakes): setup

### PR DESCRIPTION
**Pull request by ghost**
## Purpose 

~~~
nix build . # build locally to ./result/clojure-lsp
nix check . # run tests
~~~

So far upstream 2021.09.30-15.28.01 derivation has been built without issues on my machine.

## TODOs

- [ ] Fix 'Failed to create directory ./graalvm11-ce-lib/lib/lmdb/..' 
  ~~~
    Fatal error:java.lang.ExceptionInInitializerError
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
            at com.oracle.svm.util.ReflectionUtil.newInstance(ReflectionUtil.java:94)
            at com.oracle.svm.hosted.c.NativeLibraries.makeContext(NativeLibraries.java:488)
            at com.oracle.svm.hosted.c.NativeLibraries.loadJavaMethod(NativeLibraries.java:376)
            at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1542)
            at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1072)
            at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
            at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
            at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
    Caused by: java.lang.IllegalStateException: Failed to create directory /nix/store/lg9ncnimvd1770p9l7q4rmgv4cn00r0g-graalvm11-ce-lib/lib/lmdb/libraries/liblmdb
            at datalevin.ni.Lib$Directives.<clinit>(Lib.java:123)
            ... 16 more
    [clojure-lsp:57307]      [total]:   7,040.02 ms,  0.94 GB
    # Printing build artifacts to: /private/tmp/nix-build-clojure-lsp-master.drv-0/5qy3y2v6msb5r15saqg0lw344ynp31h1-source/clojure-lsp.build_artifacts.txt
    Error: Image build request failed with exit status 1
    com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
            at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
            at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
            at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)
            at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)
  ~~~

- [ ] Build jar locally
  ~~~
    Failed to read artifact descriptor for org.clojure:clojure:jar:1.10.3
    org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.clojure:clojure:pom:1.10.3 from/to central (https://repo1.maven.org/maven2/): /var/empty/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.pom.part.lock (No such file or directory)
  ~~~

### CODE REVIEW

**Comment by ericdallo** [comment]
@kkharji need any help?

**Comment by kkharji** [comment]
> @kkharji need any help?

Kinda, not sure with what exactly, but I haven't got the time to try and fix the bugs I have. I will postpone the PR for another week but till then if you have any comments or suggestions I will be happy to go over and discuss.

**Comment by ericdallo** [comment]
> Kinda, not sure with what exactly, but I haven't got the time to try and fix the bugs I have. I will postpone the PR for another week but till then if you have any comments or suggestions I will be happy to go over and discuss.

no problem, I'll take a look and try to fix the current issues

**Comment by kkharji** [comment]
okay, I'm back it at with new error 😆 

```
Fatal error:java.lang.NoSuchMethodError: 'org.graalvm.compiler.options.OptionDescriptor org.graalvm.compiler.options.OptionDescriptor.create(java.lang.String, org.graalvm.compiler.opt
ons.OptionType, java.lang.Class, java.lang.String, java.lang.Class, java.lang.String, org.graalvm.compiler.options.OptionKey, boolean, java.lang.String)'                              
        at org.graalvm.compiler.code.DataSection_OptionDescriptors.get(DataSection_OptionDescriptors.java:17)                                                                          
        at org.graalvm.compiler.code.DataSection_OptionDescriptors$1.next(DataSection_OptionDescriptors.java:44)                                                                       
        at org.graalvm.compiler.code.DataSection_OptionDescriptors$1.next(DataSection_OptionDescriptors.java:35)                                                                       
        at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:76)                                                                                  
        at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:60)                                                                                          
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:259)                                                                            
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)                                                                                 
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)                                                                                  
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)                                                                         
     [total]:   5,574.52 ms,  0.94 GB                                                                                                                                                  
Error: Image build request failed with exit status 1                                                                                                                                   
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1                                                                                      
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)                                                                                                          
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)                                                                                                              
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)                                                                                                       
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)                                                                                                               
```

**Comment by ericdallo** [comment]
@kkharji sorry, yesterday I made some improvements :) 
https://github.com/clojure-lsp/clojure-lsp/pull/635
It's already working, but I'd like to make the jar build work as well

**Comment by ericdallo** [comment]
@kkharji feel free to open a PR targeting my branch or whatever you think is best

**Comment by kkharji** [comment]
```java 
building
Error building classpath. Failed to read artifact descriptor for org.clojure:data.json:jar:2.4.0
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.clojure:data.json:jar:2.4.0
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
        at clojure.tools.deps.alpha.extensions.maven$fn__1061.invokeStatic(maven.clj:132)
        at clojure.tools.deps.alpha.extensions.maven$fn__1061.invoke(maven.clj:122)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at clojure.tools.deps.alpha$expand_deps$children_task__754$fn__756$fn__757.invoke(alpha.clj:406)
        at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:35)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.clojure:data.json:pom:2.4.0 from/to central (https://repo1.maven.org/maven2/): /var/empty/.m2/repository/org/clojure/data.json/2.4.0/data.json-2.4.0.pom.part.lock (No such file or directory)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
        ... 12 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.clojure:data.json:pom:2.4.0 from/to central (https://repo1.maven.org/maven2/): /var/empty/.m2/repository/org/clojure/data.json/2.4.0/data.json-2.4.0.pom.part.lock (No such file or directory)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
        ... 15 more
Caused by: java.io.FileNotFoundException: /var/empty/.m2/repository/org/clojure/data.json/2.4.0/data.json-2.4.0.pom.part.lock (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:138)
        at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:82)
        at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:70)
        at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:268)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:442)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        ... 20 more
```

debugging ..... god nix + clojure need some type of wrapper like https://github.com/adisbladis/vgo2nix.

**Comment by ericdallo** [comment]
Yeah, the issue is that no one has ever made a derivation using cached clojure deps, this would be the first 😅 
But That error means that the fetchedClojureDeps missed some deps that it used later, make sure to use the same aliases to fetch the same deps

**Comment by bendlas** [comment]
> Yeah, the issue is that no one has ever made a derivation using cached clojure deps, this would be the first sweat_smile But That error means that the fetchedClojureDeps missed some deps that it used later, make sure to use the same aliases to fetch the same deps

I've had success packaging deps.edn with https://github.com/hlolli/clj2nix

Maybe that can be applied here?

**Comment by ericdallo** [comment]
@bendlas sounds great! I didn't know about that, I think this PR is stale because of those issues with deps.edn/maven download, feel free to continue/open a new one

**Comment by ericdallo** [comment]
Closing this as it was implemented on https://github.com/clojure-lsp/clojure-lsp/pull/999

**Pull request closed without merging**
