### PR TITLE
Extend move-coll-entry to elementwise movements

### PR DESCRIPTION
**Pull request by mainej**
Originally `move-coll-entry` moved elements in vectors and maps in a pairwise fashion. This extends `move-coll-entry` so that it will move element-wise instead.  That is, it will move a pair of elements in some situations but a single element in others. It tries to be smart about which situation it is being called in. It will move pairwise in maps and vectors that establish bindings, and element-wise in sets, lists and regular vectors.

As before, it does its best to preserve comment affiliation. Comments will be kept near the element as it moves, including comments that appear on the lines before an element or a comment at the end of the same line as the element.

/cc @snoe, who originally suggested this addition to move-coll-entry in #684.

### CODE REVIEW

**Comment by mainej** [comment]
FWIW, I could have implemented this as separate actions: two for pairwise up/down and two for element-wise up/down, which would mean four keybindings. Having separate keybindings is more precise, but I'd rather commit one pair of keybindings to muscle memory, which is why I made element-wise movement an extension of move-coll-entry. There's a small chance it won't cover every use-case (like swapping keys with values) but personally I'm OK with doing that the old fashioned way.

**Comment by ericdallo** [comment]
@mainej sounds great to me, thank you! I'll take a look tonight and test it

**Comment by mainej** [comment]
@ericdallo I've pushed a few clean-ups to this PR. Since doing that one of the integration tests fails intermittently. I _think_ it's just a flaky test, but it's possible something I changed broke it. Let me know if I can help track down the problem.

**Comment by ericdallo** [comment]
@mainej, unfortunately, we have one or other flaky integration-test, but usually re-runing fix it.
Also, I'll test your changes right now

**Comment by ericdallo** [comment]
Thank you for the huge contribution!
Looks good to me and I didn't find any issues manually testing it

**Comment by mainej** [comment]
Great, thanks @ericdallo! And thanks for fitting this review in between the big refactoring you have going on. Looks like lots of changes!

**Comment by ericdallo** [comment]
Yes, I hope that help in the future we break the project or separate features for a more modular project :)

**Pull request merged**
