### PR TITLE
Fix truncation of namespaced keywords

### PR DESCRIPTION
**Pull request by mathieuroblin**
- [X] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- [X] I updated documentation if applicable (`docs` folder)

Here is a fix to https://github.com/clojure-lsp/clojure-lsp/issues/1637

A few questions remains:
1. I am not sure I provided enough tests, should this be tested at any other level?
2. I tried to stay as faithful to the original implementation as possible. I assumed the orignal use of `name` was to loose the leading `:` so I added an alternative path if the keyword is namespaced but still using the same keyword functions in case there is something else I am not aware of.
3. I never used `lein` before, is there a similar treatment to do? Or the `+` aliases of `lein` follow their own convention?
4. I didn't edit the changelog yet as I am not sure what is the process, I don't think I've seen it in the link you provided. Assuming the commit short message is good enough, should I paste it under `Unreleased` -> `General`?

### CODE REVIEW

**Comment by mathieuroblin** [comment]
I am not 100% sure why the `lint` step is failing, running `bb lint` locally I don't have the errors showing up.

**Comment by ericdallo** [comment]
the lint in CI is failing, I need to fix that somehow

**Comment by ericdallo** [comment]
@mathieuroblin could you add a entry to the CHANGELOG under general section please?

**Review by ericdallo — APPROVED** [review]
THank you!

**Pull request merged**
