### PR TITLE
Install script: account for uname -m being arm64 on macos m1

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
thanks, I missed that one

**Comment by ericdallo** [comment]
Actually, I remember why I didn't change that yet, that won't work with previous versions right @borkdude ? we would need to compare versions just like babashka does right?

**Comment by borkdude** [comment]
Oh, right

**Comment by ericdallo** [comment]
I mean, I think most people install latest release which wouldn't be a issue, so not sure

**Comment by borkdude** [comment]
Maybe we can support the `--arch` option so people can override it for older versions.

**Pull request merged**
