### PR TITLE
Turn off async custom linters in integration tests

### PR DESCRIPTION
**Pull request by mainej**
In an attempt to fix flaky tests #704.

### CODE REVIEW

**Comment by mainej** [comment]
This is just an experiment for now. I'm curious whether the integration tests will be green. If they are, I'll bump it several times to see if they stay green.

**Comment by mainej** [comment]
See all test runs here: https://github.com/clojure-lsp/clojure-lsp/actions/workflows/ci.yml?query=branch%3Async-custom-linters-in-integration-tests

**Comment by mainej** [comment]
OK, let me summarize my thinking here... Almost all of the recent integration test failures are related to linting unused-public-vars. I remembered that `:clojure-lsp/unused-public-var` is a custom clj-kondo linter implemented by clojure-lsp. And looking at the custom linter, I saw that it has an async version, which is enabled by default. On a hunch, I turned off that settting, making the custom linter synchronous in the integration tests.

Then I ran the integration tests several times.

At this point there have been six runs of the integration test matrix on this branch. Five out of six passed. The one failure was a timeout waiting for a response to [this linked-editing-range request](https://github.com/clojure-lsp/clojure-lsp/blob/c1890e53e54b8e553124fa0c9ffd935d6013f3e0/cli/integration-test/integration/linked_editing_range_test.clj#L22). There were no failures related to unused-public-vars.

So, I think this suggests that a lot of the flakiness is related to the async custom linter. I'm not sure that turning it off is the right way to fix the flakiness, but at least we have a lead.

**Review by ericdallo — APPROVED** [review]
I'm totally OK disabling it for integration-tests, thanks for the finding!

**Pull request merged**
