### PR TITLE
WIP - Handle classpath lookup on Windows without config change

### PR DESCRIPTION
**Pull request by bpringe**
This is a work in progress, and also includes showing an error message via `window/showMessage` when the classpath lookup fails, the the user of the client is immediately made aware something went wrong.

### CODE REVIEW

**Comment by ericdallo** [comment]
Hey @bpringe really thanks for the PR, but I'm finishing the fix for #237 and adding the window message 😅 
I didn't know you would take a look on this, sorry

**Comment by ericdallo** [comment]
I will push the fix in some minutes!

**Comment by ericdallo** [comment]
Done here: https://github.com/clojure-lsp/clojure-lsp/commit/1d8a0fb065cd44be14d3d169892df9aaed614459

**Comment by bpringe** [comment]
No problem! I got a little more practice with developing using the repl connected to Calva. Had fun calling `.showMessage` from the repl in clojure-lsp and seeing it pop up in Calva :smile:

**Comment by ericdallo** [comment]
Nice! yeah, developing with the connected REPL is very handy!

**Pull request closed without merging**
