### PR TITLE
Fix uri->filename not fully decoding URI

### PR DESCRIPTION
**Pull request by LuisThiamNye**
I found that clojure-lsp was not loading my project's .lsp/config.edn file. This was because the project's root path contained whitespace, and so the `%20` in the URI was not correctly being decoded into the correct path by the `uri->filename` function.

### CODE REVIEW

**Comment by ericdallo** [comment]
@LuisThiamNye could you check the tests failling?

**Comment by LuisThiamNye** [comment]
The tests use "file://c.clj", which is causing those problems. Should this not be considered an invalid file URI scheme?

**Comment by ericdallo** [comment]
@LuisThiamNye, I think the correct one is `file:///c.clj`, most tests use this one and I know this works with real paths

**Comment by LuisThiamNye** [comment]
As I am assuming something like `file://c.clj` would never need to be processed, I updated the tests.

I also added an additional test for the original change.

**Review by ericdallo — APPROVED** [review]
LGTM! 

@bpringe, maybe this should fix that issue with some windows users?

**Comment by bpringe** [comment]
@ericdallo You mean this one? https://github.com/BetterThanTomorrow/calva/issues/1050

**Pull request merged**
