### PR TITLE
Destructure keys

### PR DESCRIPTION
**Pull request by mainej**
Adds a refactoring to destructure keys. Similar to https://github.com/clojure-emacs/clj-refactor.el/wiki/cljr-destructure-keys.

@snoe this doesn't address everything in https://github.com/clojure-lsp/clojure-lsp/issues/905, but it's a start. Is this feature set enough for a first draft?
- Also destructures syms, although they're rare in most Clojure code.
- Available either from a local usage or definition. 
- Destructures `(:type map)` but not `(get map :type)`. (I think it would be good to do #904 as an orthogonal feature—useful in its own right.)
- Does not handle strs.
- Does not try to detect [clashing bindings](https://clojure.org/guides/destructuring#_namespaced_keywords), where both `:person/name` and `:company/name` are destructured. If this happens, users will get a lint warning.
- Does not complain if there is nothing to destructure.

Destructuring permits many styles of writing the local definitions. This PR generally follows the styles used in the [Clojure docs](https://clojure.org/reference/special_forms#associative-destructuring) on this subject:

- local definitions become symbols, when possible
  - `(:type map)` -> `{:keys [type]}`
  - `(:ns/type map)` -> `{:keys [ns/type]}`
  - `('type map)` -> `{:syms [type]}`
  - `('ns/type map)` -> `{:syms [ns/type]}`
- otherwise, auto-resolved qualified keywords maintain their form
  - `(::alias/type map)` -> `{:keys [::alias/type]}`
  - `(::type map)` -> `{:keys [::type]}`

This PR doesn't implement the special destructuring forms introduced in Clojure 1.9, which allow `{:ns/keys [type]}` and similar. This is largely personal preference—I find it hard to grep for keys when they've been destructured that way. But, if the community has strong preferences, as I suspect they might, we can introduce settings for other styles.

- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- [x] I updated documentation if applicable (`docs` folder)

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
Looks pretty good to me!

We could consider extending it to allow calling this on `let`s, probably not a common usage though

**Review by snoe — APPROVED** [review]
This is really great! Thanks @mainej

**Comment by mainej** [comment]
> consider extending it to allow calling this on lets

@ericdallo will you clarify? I'm confused because it already works on `let`—or anywhere that defines a local, like `loop`, `for`, `(for :let)`, etc.

**Comment by ericdallo** [comment]
Oh, true, I missed that!

**Pull request merged**
