### PR TITLE
Symbol analysis

### PR DESCRIPTION
**Pull request by borkdude**
- [x] Fixes https://github.com/clojure-lsp/clojure-lsp/issues/1446
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by borkdude** [comment]
@ericdallo Please let me know if I should squash the commits of if you are going to squash them when merging

**Comment by mainej** [comment]
This is exciting! Will at address #1246? Is https://github.com/clj-kondo/clj-kondo/issues/1576 also fixed?

**Comment by borkdude** [comment]
Not exactly. The only thing this does is give locations for quoted qualified symbols and an additional `:to` field which contains a namespace to which the qualified symbol might refer to (given the aliases in the same namespace). This helps navigation for symbols like `:exec-fn clojure.core/prn` and `(requiring-resolve 'clojure.core/inc)`, but that's about it.

**Review by ericdallo — APPROVED** [review]
Looks good, tested and it works great!
I'll add support for references on master, thank you @borkdude !

**Pull request merged**
