### PR TITLE
Fix for duplicate edits in cljc keyword renaming

### PR DESCRIPTION
**Pull request by rvlo**
Renaming ::click to ::click-now was resulting in ::click-now-now in cljc
files because clj-kondo analysis includes duplicate entries, one with
{:lang :clj} and another with {:lang :cljs}

### CODE REVIEW

**Comment by ericdallo** [comment]
Nice, would you mind creating an integration test for that case as well?

**Comment by rvlo** [comment]
> Nice, would you mind creating an integration test for that case as well?

Not at all. Just changed clj files to cljc. Without the fix, we get duplicate edits. With the fix, it works as expected.

**Review by ericdallo — APPROVED** [review]
LGTM, @rvlo to merge, could you add an entry in `CHANGELOG.md`?

**Comment by rvlo** [comment]
Like this?

**Pull request merged**
