### PR TITLE
Support JS libs in completion and add-require-suggestion

### PR DESCRIPTION
**Pull request by Deraen**
Investigation for #1586

### CODE REVIEW

**Review by ericdallo — COMMENTED** [review]
Looks pretty good!

I just noticed the code actions still mention the requires without the quotes, do you think we can make that work too?
image

**Comment by Deraen** [comment]
No problem, just need to check the `js-require` property in code-actions formatting. For these actions the suggestion is already from `find-namespace-suggestions` so it has the property.

Added with a test case now.

**Comment by Deraen** [comment]
Seems like `:refer` completion doesn't work yet:

```
            ["@mui/x-data-grid-pro" :refer [DataGridPro GridActionsCellItem GridToolbar GridLogicOperator]]
            ["react-dropzone-new" :refer [useDropzone]]
```

and either `DataGridPro` or `useDropzone` don't provide autocomplete suggestions of code-actions. But maybe lets make a new issue about that and solve that later?

I guess `refer` code actions are based on knowing the contents of Clojure namespaces, and not the existing refers in the project, so it would require more changes to support this for JS libs. And autocomplete doesn't seem to provide suggestions like these for Clojure either.

**Comment by Deraen** [comment]
While the tests are OK, while using debug-cli binary I noticed I'm getting wrong require forms for non-JS namespaces from add-require code-action.

**Comment by Deraen** [comment]
Okay, I see the problem. Code-action is storing the arguments for `refactor :add-require-suggestion` into arguments option, and that doesn't keep the types. I will probably need to add a new parameter to that call.

**Comment by ericdallo** [comment]
@Deraen I think found a bug testing this, I tried to require `clojure-lsp.logger` require via code action on Emacs and then it was added as: `["clojure-lsp.logger" :as logger]` with quotes

**Comment by Deraen** [comment]
@ericdallo Was that with fix from [19dab26](https://github.com/clojure-lsp/clojure-lsp/pull/1587/commits/19dab26583e58ab1a97439ece53c4c61f6cab15c) because that should have fixed just that? I wasn't able to reproduce the problem e.g. in `lib/src/clojure_lsp/clj_depend.clj` removing the logger require and adding it back using code action.

**Comment by ericdallo** [comment]
I'll double check that, maybe I was in a older commit, can't recall right now, besides that, is this PR ready to review/testing?

**Comment by Deraen** [comment]
Yes, ready for review and testing. I've been using this for over a week now.

**Comment by ericdallo** [comment]
@Deraen I'll test the new version now, but I merged a PR that it seems caused some conflicts. could you resolve the conflicts, please?

**Comment by Deraen** [comment]
@ericdallo Rebased and should be working still based on a quick test.

**Comment by ericdallo** [comment]
@Deraen could you fix the [failing lint task](https://github.com/clojure-lsp/clojure-lsp/actions/runs/7930724582/job/21653561736?pr=1587)?

**Review by ericdallo — APPROVED** [review]
Looks great, tested and it works! thanks for the help!

**Pull request merged**
